---
version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 3
    groups:
      artifact-handling:
        patterns:
          - "actions/download-artifact"
          - "actions/upload-artifact"      

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 3
    allow:
      - dependency-type: "all"      
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
    groups:
      development-dependencies:
        dependency-type: "development"
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directories: 
      - "**/*"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 3
