---
# We'll turn them on again later - but turn a number off for now.
# Priority will be given to security, github actions, JS and MD. Then CSS, then secondary other files.
DISABLE_LINTERS: 
  - COPYPASTE_JSCPD
  - DOCKERFILE_HADOLINT
  - REPOSITORY_CHECKOV
  - REPOSITORY_TRIVY
  - REPOSITORY_KICS
  - C_CPPLINT
  - CPP_CPPLINT
  - CSS_STYLELINT
  - HTML_HTMLHINT
  - JSON_JSONLINT
  - JSON_PRETTIER
  - JAVASCRIPT_STANDARD
  - MARKDOWN_MARKDOWN_TABLE_FORMATTER
  - MARKDOWN_MARKDOWNLINT
  - YAML_PRETTIER
  - YAML_YAMLLINT
  - PYTHON_ISORT
  - PYTHON_RUFF
  - SPELL_CSPELL
