---
layout: page
title: Dead Metal
date: 2005-03-01 16:09:42
---
<p>Dead Metal is one of the <a class="wiki" href="/wiki/robot_wars.html" title="The british robot smashing TV series.">Robot Wars</a> House Robots<a class="wiki wikinew for-review" title="Create page: House Robots">?</a>. At a relatively light 112 kg, his gripping claws are a menace to robots not fast enough to elude his grasp. Once he has you - his usal tactic is then to sink his 3000 Rpm Circular Cutter into you. Nice.... I love to see the sparks fly when he chomps into some poor wandering contender - thus living up to his namesake and rendering them into dead metal.
</p>
<p>With a top speed of 112 mph form his battery driver motors, he ambles like some monstrous nightmare crustacean accross the arena. He is 70cm high, and 160cm long by 100cm wide. Impressive stats - but still dwarfed by his big brother Sir Killalot<a class="wiki wikinew for-review" title="Create page: Sir Killalot">?</a>.
</p>
<p>He has spikes and ribs for armour, with some mesh to fend off lighter blows. The meshes are not all that strong, and quite a lot of his tender insides are exposed - an attack from above at the rear would be quite effective. He also has slightly high ground clearance - exposing him to a good flipping.
<br/><img class="img-responsive" src="image177"/>
<br/>He has been known to loose his cutting wheel - sending it flying across the arena before.
</p>
<table class="normal" id="fancytable_1"> <tr> <td class="odd"> <a class="internal" href="http://www.amazon.co.uk/exec/obidos/ASIN/B00006G9Y0/orionrobots-21" target="_blank"> <img class="img-responsive" src="image29"/> </a> </td> <td class="odd"> <a  href="http://www.amazon.co.uk/exec/obidos/ASIN/B00006G9Y0/orionrobots-21" rel="external" target="_blank">Robot Wars DVD Box Set</a> </td> <td class="odd"> If you are a real fan, you would probably want to get to know these robots well. The DVD's feature huge numbers of battles, as well as under the hood and many extras. If you are building - you could use this to your advantage to study the weapons, weaknesses and strategies of other teams.</td> </tr> <tr> <td class="even"> <a class="internal" href="http://www.amazon.co.uk/exec/obidos/ASIN/B00008UEMW/orionrobots-21" target="_blank"> <img class="img-responsive" src="image80"/> </a> </td> <td class="even"> <a  href="http://www.amazon.co.uk/exec/obidos/ASIN/B00008UEMW/orionrobots-21" rel="external" target="_blank">Robot Wars: Arenas of Destruction... - PC CD Rom</a> </td> <td class="even"> If you are interested in robots, battling robots and similar - but you are not quite ready to make the step into building your own yet, you could always live it out in this PC game. There are versions for other platforms. Although it is fun, and some degree of robot customization is available - it doesnt have anything on the real thing.</td> </tr> <tr> <td class="odd"> <a class="internal" href="http://www.amazon.co.uk/exec/obidos/ASIN/B00006LJZI/orionrobots-21" target="_blank"> <img class="img-responsive" src="image81"/> </a> </td> <td class="odd"> <a  href="http://www.amazon.co.uk/exec/obidos/ASIN/B00006LJZI/orionrobots-21" rel="external" target="_blank">Robot Wars 2 - Extreme Destruction</a> </td> <td class="odd"> This Gameboy Advance title is good fun. In a workshop system - you must consider the normal power, vs armour, vs weight, vs offense trade-offs, you get to battle robots (including the house-robots) in a number of interesting arenas in simple 3D. You eventually get to design your own arenas. Once you have unlocked(by battling) a number of good mods, and designed a good robot - you can use these in battles with other players with a link cable. This is also available for the X-Box and PC.</td> </tr> </table>
