---
layout: page
title: MultiMeter
date: 2005-08-23 23:01:52
---
<p>If you are building the electronic guts of many robots, you will often need to test circuit function and component values.
</p>
<p>Having, and knowing how to use a multimeter is an invaluable skill.
<br/>The first peice of advice I will offer any new robot builders is to buy a Digital one.  Analog ones are awkward to read, not very precise, and to be frank a bit obsolete.
</p>
<p>Entry level multimeters should cost no more than around £15 (less if you really look around at computer markets). They should also come with one set of probes - though eventually you might think about getting others. Also consider how many digits it will display - again- for entry level, four should be sufficient. If a manufacturer specifies 3.5 - they mean the first digit can only display a 1.
</p>
<p>Most multimeters have enough functionality to read resistance, current and voltage.
</p>
<p>Since resistors are one of the most common components you are working with - you will regularly use this one. All the settings marked with the Ohm Symbol &amp; are resistor markings. There are a set of different <a class="wiki" href="/wiki/resistor.html" title="Resistor">resistor</a> value ranges, so you try and go with the nearest one - or start low.  If you test the resistance, and see NO or 1, try shifting up to a higher setting.  Most go from 1&amp;ohm; (on the 2&amp;ohm; setting) up to 2M&amp;ohm; - this is a very high resistance, and although I have seen them, it is very rare you will use a resistor over this rating. For each setting- you are able to measure resistances less than, or equal to it. Some meters are "Auto-Ranging" - so you do not have to select a setting. Even if you are familiar with the resistor colour bands, I often check the resistance anyway, because some resistors (especially if salvaged) may be damaged and offer a much higher, or lower one than printed. If you are totally trusting of the colour bands, and do not check - you may find you have to desolder a dud.
</p>
<p>The next tool you will regularly use is continuity checking. It is often very worthwhile knowing if a circuit, or cable is clear-flowing and not broken. On some multimeters- you will have a specific setting, and an <a class="wiki" href="/wiki/led.html" title="Light Emitting Diode">LED</a> or Tone which sounds when the check is successful. On others- many of the entry-level ones, you can use the <a class="wiki" href="/wiki/diode.html" title="Diode">diode</a> test functionality.
</p>
<table class="normal" id="fancytable_1"> <tr> <td class="odd"> <a class="internal" href="http://www.amazon.co.uk/exec/obidos/ASIN/B0001K9XKW/orionrobots-21" target="_blank"> <img class="img-responsive" src="image57"/> </a> </td> <td class="odd"><a  href="http://www.amazon.co.uk/exec/obidos/ASIN/B0001K9XKW/orionrobots-21" rel="external" target="_blank">Digital Multimeter With Backlight</a></td> <td class="odd">Draper</td> <td class="odd">You might not use the backlight much but there will definately be situations where you will have wondered how you did without it. I prefer this rotary kind of MultiMeter. Ensure you buy a digital one like this as the analogue ones really do not live up to what a roboticist will require.  It is cheaper from Amazon than many local tool shops -  and has all of the beginner functions for measuring resistance, current and voltage. It also has Diode and Transistor testing.</td> </tr> <tr> <td class="even"> <a class="internal" href="http://www.amazon.co.uk/exec/obidos/ASIN/0859341844/orionrobots-21" target="_blank"> <img class="img-responsive" src="image58"/> </a> </td> <td class="even"><a  href="http://www.amazon.co.uk/exec/obidos/ASIN/0859341844/orionrobots-21" rel="external" target="_blank">Getting the Most from Your Multimeter...</a></td> <td class="even">R.A. Penfold</td> <td class="even">If you are serious about using a multimeter- or interested in using one for more purposes - this is a great little book - at less than a fiver, why not. OrionRobots has a collection of the R.A. Penfold books - which while small, come highly recommended.</td> </tr> <tr> <td class="odd"> <a class="internal" href="http://www.amazon.co.uk/exec/obidos/ASIN/0072226013/orionrobots-21" target="_blank"> <img class="img-responsive" src="image16"/> </a> </td> <td class="odd"> <a  href="http://www.amazon.co.uk/exec/obidos/ASIN/0072226013/orionrobots-21" rel="external" target="_blank">Junkbots, Bugbots and Bots on Wheels: Building Simple Robots with BEAM Technology</a> </td> <td class="odd"> Dave Hrynkiw, Mark W. Tilden </td> <td class="odd"> I recommend this book again - as it has a neat little section on using a multimeter and other electronic stuff. Since you can build robots with it as well - you should probably have this in your library.</td> </tr> </table>
