FROM ubuntu:trusty
RUN apt-get -y update && apt-get install --only-upgrade -y ca-certificates
RUN apt-get -y update && apt-get install -y linkchecker
RUN apt-get -y update && apt-get install -y python-pip
RUN pip install jinja2


